# Simple workflow for deploying static content to GitHub Pages
name: Initiate Docs Deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # Clone the other repository
      - name: Checkout Other Repository
        uses: actions/checkout@v3
        with:
          repository: "username/other-repo"
          token: ${{ secrets.GH_RELEASE_BUILDUSERSICKAG }}
          path: "docs-repo"

      # Copy built docs to the other repo
      - name: Copy Built Docs to Other Repo
        run: mkdir -p ./docs-repo/www && cp -r ./main-repo/packages/docs/dist/* ./docs-repo/www

      # Commit and Push Changes
      - name: Commit and Push to Other Repo
        run: |
          cd ./docs-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update docs"
          git push
