name: Quality Gate

on: pull_request

jobs:
  quality-gate:
    name: Install and verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.12
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Check for uncommitted changes
        run: git diff --exit-code

      - name: Lint
        run: pnpm lint

      - name: Check for uncommitted changes
        run: git diff --exit-code

      - name: Vendorism
        run: cd packages/components && pnpm vendor.get && pnpm vendor.set

      - name: Check for uncommitted changes
        run: git diff --exit-code

      - name: Tests
        run: pnpm test -r
        # @see https://github.com/microsoft/playwright/issues/6500
        env:
          HOME: /root
